
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins

title: Kabileshwaran | Learning in Public
description: A public record of my daily learnings, projects, and core Computer Science concepts as a Computer Science undergraduate.

url: "https://kabileshwarankabil.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author: Kabileshwaran

markdown: kramdown
minimal-theme-mode: auto
