remote_theme: cotes2020/jekyll-theme-chirpy

title: Kabileshwaran | Learning in Public
description: A public record of my daily learnings, projects, and core Computer Science concepts as a Computer Science undergraduate.
url: "https://kabileshwarankabil.github.io"

author:
  name: Kabileshwaran
  links:
    - https://github.com/KabileshwaranKabil
    - https://www.linkedin.com/in/m-kabileshwaran-4018a5378/

timezone: Asia/Kolkata

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives

paginate: 10

markdown: kramdown

theme_mode: dark
