# The Site Configuration

theme: minima

minima:
  skin: auto

lang: en

timezone: Asia/Kolkata

title: Kabileshwaran | Learning in Public

tagline: Daily learnings, technical notes, and projects from my CS journey

description: >-
  A public record of my daily learnings, projects, and core Computer Science concepts as a Computer Science undergraduate.

url: "https://kabileshwarankabil.github.io"

github:
  username: KabileshwaranKabil

social:
  name: Kabileshwaran
  email: kabileshwaran@example.com
  links:
    - https://github.com/KabileshwaranKabil
    - https://www.linkedin.com/in/m-kabileshwaran-4018a5378/

paginate: 10

baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

markdown: kramdown

# 404 Page Configuration
404_error_page: 404.md

# Exclude files from processing
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include dotfiles
include:
  - .htaccess
